### ISSUE TITLE
Any plans of migrating from llvm-py to llvmlite?

### ISSUE THREAD

**Issue by sowani** [ContinuumIO/llvmmath#12]
One of llvmmath dependencies is llvm-py (https://github.com/llvmpy/llvmpy) which is not obsolete and has been replaced by llvmlite (https://github.com/numba/llvmlite). Are there any plans of migrating llbmmath to utilize llvmlite instead of llvm-py? Thanks!

**Comment by markflorisson** [comment]
Hi @sowani, I'm not sure if anyone is still using this project or maintaining it. If you want to use the project, perhaps it's better to fork it?

**Comment by seibert** [comment]
Yes, this project is not active anymore.

**Comment by sowani** [comment]
Thanks @markflorisson  and @seibert This project as also included in my list of packages to be ported to ppc64le, but with latest update I will drop it from my list.
